version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27000:27017"  # Exposing MongoDB on port 27000
    networks:
      - mynetwork

  app:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork: